baseURL: https://example.com
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Jane Doe - Nutrition Coach & Chef Consultant
params:
  copyright: © Jane Doe
  description: Nutrition Coach & Chef Consultant
  favicon: images/favicon.png
  images: images/cover-image.jpg
  meta:
    keywords: some, keywords, for, seo, you, know, google, duckduckgo, and, such
  title: Jane Doe - Nutrition Coach & Chef Consultant
