baseURL: https://demo.gethugothemes.com/educenter/
title: DCI | Design Thinking, Coaching, and Innovative Classroom Designing
theme: educenter-hugo
paginate: '6'
summaryLength: '10'
disqusShortname: []
disableLanguages: []
params:
  address: 254 ถนนพญาไท แขวงวังใหม่ เขตปทุมวัน กรุงเทพฯ 10330
  author: DCI Team
  contact_form_action: '#'
  cookies:
    enable: no
    expire_days: 2
  description: This is meta description
  email: upskill.reskill.educhula@gmail.com
  google_analitycs_id: ''
  logo: images/logo2.png
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  mobile: ' '
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/animate/animate.css
      - link: plugins/venobox/venobox.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/venobox/venobox.min.js
      - link: plugins/filterizr/jquery.filterizr.min.js
      - link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - icon: ti-facebook
      link: '#'
      title: facebook
  subscription:
    enable: no
    mailchimp_form_action: https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
  top_header: no
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2022 DCI Team by [Faculty of Education, Chulalongkorn University](https://www.facebook.com/profile.php?id=100069330084205)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      footer:
        - name: ทีมบริหารจัดการหลักสูตร
          url: teacher
        - name: ข่าวสาร/ประกาศ
          url: scholarship
        - name: กำหนดการอบรม
          url: event

      main:
        - name: เกี่ยวกับหลักสูตร
          url: "about"
          weight: 1
        - hasChildren: yes
          name: Mores
          weight: 2
        - name: สรุปการเรียนรู้ของผู้เข้าอบรม
          parent: Mores
          url: author/john-doe/
        - name: กำหนดการ
          parent: Mores
          url: event
        - name: ผลผลิตของหลักสูตร
          parent: Mores
          url: research
        - name: ความรู้เผยแพร่
          url: blog
          weight: 4
    weight: 1